
version: '2.1'
services:
  node-red:
    container_name: "nodered"
    restart: unless-stopped
    build: node-red
    user: "root"
    ports:
      - "1880:1880"
    volumes:
      - "./data/nodered:/data"
    links:
      - influxdb

  mosquitto:
    container_name: "mosquitto"
    image: ansi/mosquitto
    user: "root"
    links:
      - influxdb
    ports:
        - "1883:1883"

  influxdb:
    container_name: "influxdb"
    restart: unless-stopped
    image: influxdb:1.2.4
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb/types.db:/usr/share/collectd/types.db:ro

    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
      - "2003:2003"

  grafana:
    #login: m2m
    #psswd: m2gi_2018
    container_name: "grafana"
    restart: unless-stopped
    image: grafana/grafana
    ports:
       - "3000:3000"
    volumes:
      - "./grafana:/var/lib/grafana"
    links:
      - influxdb

### end of file ###
